### PR TITLE
Fix autoconf warnings

### LINKED ISSUE #50: autoreconf generates warnings
Done on Slackware64-current Linux. Tested on dc2aa7b0fc91ef885c6ca83f1689057fd021f996 from a clean repo using autotools 2.69.

Running `autoreconf -i` produces the following warnings:

    aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
    automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
    configure.in:13: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
    configure.in:13: http://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
    configure.in:15: installing './compile'
    src/Makefile.am:6: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
    automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'

### PR DESCRIPTION
**Pull request by h3xx**
Fixes #50.

### CODE REVIEW

**Comment by h3xx** [comment]
I don't know what's going on with the CI runner; I reset the branch to master but with one non-code change and it still failed.

**Comment by aoshiken** [comment]
It seems that the GTK2 package isn't installed by default on the Ubuntu Trusty Travis build so the build step fails with:
```
[...]
checking pkg-config is at least version 0.9.0... yes
checking for PACKAGE... no
configure: error: Package requirements (gtk+-2.0 >= 2.6.0) were not met:

No package 'gtk+-2.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
[...]
```

**Comment by aoshiken** [comment]
Please, try again
I've updated the travis.yaml configuration file for installing GTK before building

**Comment by h3xx** [comment]
Okay, I rebased off bb8ec99d1e88bb534042d38c6f4842eac1373f80

**Comment by h3xx** [comment]
Unfortunately I don't think CI covers these changes; it uses the `configure` script as it exists in the repo, and doesn't generate it from the `configure.ac` file.

**Comment by aoshiken** [comment]
Don't worry, give me some days, I'm really busy

**Comment by h3xx** [comment]
See !54 which removes a few files and updates the CI.

**Comment by aoshiken** [comment]
Please, rebase again

**Comment by aoshiken** [comment]
Thanks again! :)

**Pull request merged**
